language: elixir
dist: bionic

matrix:
  include:
    - otp_release: 19.3.6.13
      elixir: 1.6.6
    - otp_release: 19.3.6.13
      elixir: 1.7.4
    - otp_release: 20.3.8.26
      elixir: 1.8.2
    - otp_release: 21.3
      elixir: 1.9.4
    - otp_release: 21.3.8.17
      elixir: 1.10.4
    - otp_release: 23.0.3
      elixir: 1.10.4

sudo: required
services: docker

addons:
  apt:
    packages:
      - git
      - build-essential
      - libtool
      - libtool-bin
      - pkg-config
      - autotools-dev
      - autoconf
      - automake
      - cmake
      - uuid-dev
      - libpcre3-dev

before_install:
  - docker pull consul
  - docker run -d -p 127.0.0.1:8500:8500 consul
  - |
    set -e

    tmpdir=$(mktemp -d) && (
      git clone --depth=1 git://github.com/zeromq/libzmq.git "$tmpdir/libzmq"
      git clone --depth=1 git://github.com/zeromq/czmq.git "$tmpdir/czmq"

      cd "$tmpdir/libzmq" && {
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
      }

      cd "$tmpdir/czmq" && {
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
      }

      rm -rf "$tmpdir"
    )

script:
  - mix format --check-formatted
  - env liblink_cflags_extra='-Wall -pedantic' mix compile
  - mix dialyzer
  - mix test

cache:
  directories:
    - _build
    - deps
