language: elixir
dist: bionic

elixir:
  - 1.6
otp_release:
  - 20.3.8
  - 20.3.8.22

sudo: required
services: docker

addons:
  apt:
    packages:
      - git
      - build-essential
      - libtool
      - libtool-bin
      - pkg-config
      - autotools-dev
      - autoconf
      - automake
      - cmake
      - uuid-dev
      - libpcre3-dev

before_install:
  - docker pull consul
  - docker run -d -p 127.0.0.1:8500:8500 consul
  - |
    set -e

    tmpdir=$(mktemp -d) && (
      git clone --depth=1 git://github.com/zeromq/libzmq.git "$tmpdir/libzmq"
      git clone --depth=1 git://github.com/zeromq/czmq.git "$tmpdir/czmq"

      cd "$tmpdir/libzmq" && {
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
      }

      cd "$tmpdir/czmq" && {
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig
      }

      rm -rf "$tmpdir"
    )

script:
  - mix format --check-formatted
  - env liblink_cflags_extra='-Wall -pedantic' mix compile
  - mix dialyzer
  - mix test

cache:
  directories:
    - _build
    - deps
